version: 2
jobs:
  build_app:
    working_directory: ~/app
    docker:
    - image: circleci/node:11
    steps:
    - checkout
    - setup_remote_docker
    - restore_cache:
        keys:
        - v1-{{ .Branch }}
        paths:
        - ~/caches/app.tar
    - run:
        name: Load Docker image layer cache
        command: |
          set +o pipefail
          docker load -i ~/caches/app.tar | true
    - run:
        name: Authenticate DockerHub
        command: |
          docker login -u ${DOCKERHUB_USERNAME} -p "${DOCKERHUB_PASSWORD}"
    - run:
        name: Build application Docker image
        command: docker build --cache-from=app -t app ./app/
    - run:
        name: Save Docker image layer cache
        command: |
          mkdir -p ~/caches
          docker save -o ~/caches/app.tar app
    - save_cache:
        key: v1-{{ .Branch }}-{{ epoch }}
        paths:
          - ~/caches/app.tar
    - deploy:
        name: Push application Docker image
        command: |
          export DOCKER_IMAGE=faizhasim/papaadamango
          docker tag app "${DOCKER_IMAGE}:${CIRCLE_SHA1}"
          docker tag app "${DOCKER_IMAGE}:latest"
          docker push "${DOCKER_IMAGE}:${CIRCLE_SHA1}"
          docker push "${DOCKER_IMAGE}:latest"

  deploy_single_ecs_cluster:
    working_directory: ~/deploy
    docker:
    - image: hashicorp/terraform:0.11.10
    steps:
    - checkout
    - run:
        name: terraform init
        command: cd terraform/single-ecs-cluster && terraform init -backend=true -force-copy -get=true -input=false
    - deploy:
        name: terraform apply
        command: cd terraform/single-ecs-cluster && terraform apply -auto-approve -var "docker_image_tag=${CIRCLE_SHA1}"

workflows:
  version: 2
  ci_only:
    jobs:
    - build_app:
        filters:
          branches:
            ignore:
              - master
  cd_test:
    jobs:
    - build_app:
        filters:
          branches:
            only: master
    - deploy_single_ecs_cluster:
        requires:
          - build_app
        filters:
          branches:
            only: master
  cd_prod:
    jobs:
    - build_app:
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v[0-9]+(\.[0-9]+)*$/
